language: go

go:
  # - "1.12.x"
  # - "1.13.x"
  - master

env:
  - GO111MODULE=on

script:
  - make build-lin-to-lin
  - make build-lin-to-osx
  - make build-lin-to-win

addons:
  apt:
    update: true
    packages:
    - libsdl2-dev
    - libsdl2-image-dev
    - libsdl2-ttf-dev
    - mingw-w64
    - zip

after_success:
  - mkdir dist
  - cd ./builds/linux && zip -r ../../dist/flappy-gopher-linux-$TRAVIS_BRANCH.zip . && cd ../..
  - cd ./builds/osx && zip -r ../../dist/flappy-gopher-osx-$TRAVIS_BRANCH.zip . && cd ../..
  - cd ./builds/windows && zip -r ../../dist/flappy-gopher-windows-$TRAVIS_BRANCH.zip . && cd ../..

deploy:
  provider: releases
  api_key:
    secure: nqQ/OgXa7ppSkXezjPOkseesf9XnLmfnC368W6oJeDrdL/1B3pxsNe1YyingOWq7VBtzLixdK43J4664n7KfasVjwC70R8wig0ucFSbqXtozLblMP8Zz+V1/QnTLutIW75kEiJVpkDbeNYC0vv4AuBNmGr2XZkR0gerIT6YL9Jjl9Z/sUjqSvwcVyj4mVNo/s4Su40kP2VWQ+jRd1iNWIa7GS4Ixo7Bc9VDFZFxo8SC26J7z9TTRfM+CnCvBQYUpoDahr8uIi9rp3oyXPloHYeO0eEjGZ4Kb27Mb6OZk1w3GZICax4zUqcWW/MdpImJR7QN7aXfNRuAHWMXj9qJCytN2z7IMP2Xv/c+jLjQxw/wQ30J7Vw+lIO2THzRhHsl4KBfy1UkEPZb6InpB7f8F736slMkETi+M75gK8SkjAv0ZrhL8CMpWmV9AIUxNFQSNqtTS17+SYDExKIbphF0acw1apZh2SjXB9Jca8ejwHDKxPG7Pr28Mvd+/3TOA6TGCxSIdvEn2yTMIpfMZ7sWh3NYljnGTJh708T17m5fqm9F1oRqcvptd/GwIvCPtZWnRiIKhAh9j2/5COJc89mp7O4ZUndsLws54Wj/zqrMSGnsUSKPBzah6/5aw7AcvdppV1wT9446Dx+JWfdizYGKQP2mpbzm7F+lQAK+dLVfHiaU=
  file:
    - ./dist/flappy-gopher-linux-$TRAVIS_BRANCH.zip
    - ./dist/flappy-gopher-osx-$TRAVIS_BRANCH.zip
    - ./dist/flappy-gopher-windows-$TRAVIS_BRANCH.zip
  skip_cleanup: true
  on:
    repo: tclemos/flappy-gopher
    tags: true
